### ISSUE TITLE
How do you swap keys

### ISSUE THREAD

**Issue by freetextmike** [oscarsanchezdm/hackintoshXPS9350#1]
Alt and windows key

**Comment by freetextmike** [comment]
its ok now i changed it on systempreferences

**Comment by oscarsanchezdm** [comment]
I accidently deleted the SSDT that swapped the keys. I have commited it again
https://github.com/oscarsanchezdm/hackintoshXPS9350/blob/main/EFI/OC/ACPI/SSDT-PS2K.aml

It's useful if your password needs an alt key, as the swap made by System Preferences does not affect the login screen.
